services:
  postgresql: 
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "test"
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
  
  # app:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     SECRET_KEY: "12345678"
  #     DATABASE_URI: "postgresql+psycopg2://tester:rdPWwp_2E89QpHOD@postgresql:5432/test"
  #   ports:
  #     - "5000:5000"